version: "3.9"
services:
  postgres:
    container_name: postgresDB2
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: likesDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    ports:
      - "5436:5432"